// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\ahdaa\GOLANG\Leuse_Ecommerce\pkg\repository\interface\inventory.go

// Package mock_interfaces is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/ahdaan98/pkg/utils/models"
	gomock "github.com/golang/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// AddInventory mocks base method.
func (m *MockInventoryRepository) AddInventory(inventory models.AddInventory) (models.InventoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInventory", inventory)
	ret0, _ := ret[0].(models.InventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInventory indicates an expected call of AddInventory.
func (mr *MockInventoryRepositoryMockRecorder) AddInventory(inventory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInventory", reflect.TypeOf((*MockInventoryRepository)(nil).AddInventory), inventory)
}

// CheckInventoryExist mocks base method.
func (m *MockInventoryRepository) CheckInventoryExist(productName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInventoryExist", productName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInventoryExist indicates an expected call of CheckInventoryExist.
func (mr *MockInventoryRepositoryMockRecorder) CheckInventoryExist(productName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInventoryExist", reflect.TypeOf((*MockInventoryRepository)(nil).CheckInventoryExist), productName)
}

// CheckInventoryExistByID mocks base method.
func (m *MockInventoryRepository) CheckInventoryExistByID(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInventoryExistByID", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInventoryExistByID indicates an expected call of CheckInventoryExistByID.
func (mr *MockInventoryRepositoryMockRecorder) CheckInventoryExistByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInventoryExistByID", reflect.TypeOf((*MockInventoryRepository)(nil).CheckInventoryExistByID), id)
}

// CheckStock mocks base method.
func (m *MockInventoryRepository) CheckStock(productID int) (models.CheckStockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStock", productID)
	ret0, _ := ret[0].(models.CheckStockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStock indicates an expected call of CheckStock.
func (mr *MockInventoryRepositoryMockRecorder) CheckStock(productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStock", reflect.TypeOf((*MockInventoryRepository)(nil).CheckStock), productID)
}

// EditInventory mocks base method.
func (m *MockInventoryRepository) EditInventory(inventory models.EditInventory, id int) (models.InventoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditInventory", inventory, id)
	ret0, _ := ret[0].(models.InventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditInventory indicates an expected call of EditInventory.
func (mr *MockInventoryRepositoryMockRecorder) EditInventory(inventory, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditInventory", reflect.TypeOf((*MockInventoryRepository)(nil).EditInventory), inventory, id)
}

// GetImages mocks base method.
func (m *MockInventoryRepository) GetImages(productID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImages", productID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImages indicates an expected call of GetImages.
func (mr *MockInventoryRepositoryMockRecorder) GetImages(productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImages", reflect.TypeOf((*MockInventoryRepository)(nil).GetImages), productID)
}

// ListProducts mocks base method.
func (m *MockInventoryRepository) ListProducts(page, per_product int) ([]models.InventoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", page, per_product)
	ret0, _ := ret[0].([]models.InventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockInventoryRepositoryMockRecorder) ListProducts(page, per_product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockInventoryRepository)(nil).ListProducts), page, per_product)
}

// ListProductsWithImages mocks base method.
func (m *MockInventoryRepository) ListProductsWithImages(page, per_product int) ([]models.InventoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsWithImages", page, per_product)
	ret0, _ := ret[0].([]models.InventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsWithImages indicates an expected call of ListProductsWithImages.
func (mr *MockInventoryRepositoryMockRecorder) ListProductsWithImages(page, per_product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsWithImages", reflect.TypeOf((*MockInventoryRepository)(nil).ListProductsWithImages), page, per_product)
}

// ShowIndividualProduct mocks base method.
func (m *MockInventoryRepository) ShowIndividualProduct(productID int) (models.InventoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowIndividualProduct", productID)
	ret0, _ := ret[0].(models.InventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowIndividualProduct indicates an expected call of ShowIndividualProduct.
func (mr *MockInventoryRepositoryMockRecorder) ShowIndividualProduct(productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowIndividualProduct", reflect.TypeOf((*MockInventoryRepository)(nil).ShowIndividualProduct), productID)
}

// UpdateInventory mocks base method.
func (m *MockInventoryRepository) UpdateInventory(inventory models.UpdateInventory, id int) (models.InventoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventory", inventory, id)
	ret0, _ := ret[0].(models.InventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInventory indicates an expected call of UpdateInventory.
func (mr *MockInventoryRepositoryMockRecorder) UpdateInventory(inventory, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventory", reflect.TypeOf((*MockInventoryRepository)(nil).UpdateInventory), inventory, id)
}

// UploadImage mocks base method.
func (m *MockInventoryRepository) UploadImage(id int, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", id, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockInventoryRepositoryMockRecorder) UploadImage(id, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockInventoryRepository)(nil).UploadImage), id, image)
}
